### ISSUE TITLE
Module 'mfrc522_i2c' has no attribute 'MFRC522'

### ISSUE THREAD

**Issue by Kevitto** [cpranzl/mfrc522_i2c#1]
Hi, I recently found your module to use RFID readers on i2c for Python, but none of your examples work, they all give me that same message: cannot import name 'MFRC522' from 'mfrc522_i2c', and so I tried to pull the attribute directly and got the title's message.

Any fix for that?

Thanks,

Kevitto

**Comment by cpranzl** [comment]
I will look into it.

**Comment by loudoweb** [comment]
I had the same error.

@cpranzl it's weird but the` __init__.py` file saved in /home/pi/.local/lib/python3.7/site-packages/mfrc522_i2c is **empty**

So I've copy paste the content from this github repo and now I don't have this error anymore.

Though I have this one now :) : 
```
line 599 in __MFRC522_write selft.i2cBus.write_byte_data(self.i2cAddress, address, value)
OSError: [Errno 121] Remove I/O error
```
EDIT: I tried with wrong i2cAdress, I can start without error now but I have no success in reading payload yet.

**Comment by cpranzl** [comment]
Hi, I've finally found the time to get again into it and quite happy to tell you that it seems that the error was found. I've released a new version, v.0.0.4, and published it on pypi.

Many thanks to hop from pyUGAT (python User Group Austria.
