### ISSUE TITLE
Question: Rock 4S

### ISSUE THREAD

**Issue by hughsheehy** [cpranzl/mfrc522_i2c#3]
Hi - this is a question not an issue. 

I'm looking at this for a Rock 4 S (same pins as all Rock 4s so slightly different from a Pi). Do I need to adjust this to work on the Rock 4? I don't see pin mappings anywhere in the code - or I'm not recognizing pin mappings anywhere in the code. 

H

**Comment by cpranzl** [comment]
Hi!

the library does not require to define the pins where the i2c bus is residing. For communication it uses SMBUS which is initialised with the number of the bus (1) and the address of the reader (0x28). In the examples this is in dump.py at lines 15,16, and 17. On the Raspberry Pi **i2c bus 1** corresponds with the **pin 3** (GPIO2/SDA1) and **pin 5** (GPIO3/SCL1).

Using the information that i found on the internet (https://wiki.radxa.com/Rock4) I assume you have an ROCK 4 SE. Which should feature three i2c buses. From the pinout I found (https://wiki.radxa.com/Rock4/hardware/gpio), I would say that these are i2c bus 2, i2c bus 6 and ic2 bus 7. Although bus number 6 is only a secondary function on the corresponding pins. Also the notes only states i2c bus 2 and bus 7.

If the SMBus library exists also for you hardware I would test it with the reader attached to **pin3 (GPIO2_A7/I2C7_SDA)** and **pin 5 (GPIO2_B0/S2C7_SCL)** and initialising with bus 7. The address keeps 0x28.

I also found this package on GitHub (https://github.com/radxa/pyRock). In the example arduinoOverI2C.py the initialisation of the i2c bus and a peripheral can be seen. When creating the object arduinoSlave in line 58 the parameters that are used are 0x04 as address and 0 as bus. 

So maybe you should use bus 0.

kr
Chris
